# Generated by Django 4.2.2 on 2024-01-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='created_timestmp',
            new_name='created_timestamp',
        ),
    ]
